#!/usr/bin/env php
<?php
set_time_limit(0);

require __DIR__ .'/bootstrap/edk.php';

$cronStartTime = microtime(true);

@error_reporting(E_ALL ^ E_NOTICE);

// load mods
loadMods();

$consoleArgs = isset($_SERVER['argv']) ? $_SERVER['argv'] : null;
if( $consoleArgs == null || count($consoleArgs) < 2 )
{
	println("Missing command line arguments");
	exit(1);
}

$task = $argv[1];

$tasks = array('Api', 
				'Cache', 
				'ClearUp',
				'Feed',
				'Value',
				'ZKB',
				);
				
if( in_array(strtolower($task), array_map('strtolower',$tasks) ) )
{
	$name = 'EDK\Command\\' . $task;
	$command = new $name;
	$command->execute();
	
	println("Time taken = ".(microtime(true) - $cronStartTime)." seconds.");
}

function println($msg)
{
	print $msg.PHP_EOL;
}